--
-- PostgreSQL database dump
--

\restrict UcqoKN0jaaiBqakSTbkvDQewS1qBrSuypKpIsJgbFBsL5FXS1PCuyVXLlm0V2So

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_edit_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_edit_requests (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    employee_name text,
    old_data jsonb,
    new_data jsonb,
    status text DEFAULT 'pending'::text,
    requested_by text,
    requested_at timestamp with time zone DEFAULT now(),
    resolved_at timestamp with time zone
);


ALTER TABLE public.employee_edit_requests OWNER TO postgres;

--
-- Name: employee_edit_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_edit_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_edit_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    name text NOT NULL,
    position_id bigint,
    system_position_id bigint,
    dept_id bigint,
    sector_id bigint,
    email text,
    intphone text,
    mobile text,
    room text,
    car_plate text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_users (
    id bigint NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    password text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.portal_users OWNER TO postgres;

--
-- Name: portal_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.positions (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.positions OWNER TO postgres;

--
-- Name: positions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sectors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sectors (
    id bigint NOT NULL,
    name text NOT NULL,
    dept_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.sectors OWNER TO postgres;

--
-- Name: sectors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sectors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sectors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_positions (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.system_positions OWNER TO postgres;

--
-- Name: system_positions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (id, name, created_at) FROM stdin;
1	Rəhbərlik	2026-08-13 14:48:22.157435+04
2	Coğrafi informasiya sistemləri və məlumatların idarə edilməsi şöbəsi	2026-08-13 14:48:22.157435+04
\.


--
-- Data for Name: employee_edit_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_edit_requests (id, employee_id, employee_name, old_data, new_data, status, requested_by, requested_at, resolved_at) FROM stdin;
\.


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, name, position_id, system_position_id, dept_id, sector_id, email, intphone, mobile, room, car_plate, created_at, updated_at) FROM stdin;
1	Cəfərov Fərid	1	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:34:32.34942+04	2026-08-13 15:09:07.084209+04
2	Alıyev Ağakişi	2	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:34:32.34942+04	2026-08-13 15:09:07.084209+04
3	Tanırverdiyev Çingiz	2	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
4	Məmmədov Razim	2	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
5	Məhəmmədov Elməddin	3	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
6	Əhmədov Elçin	8	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
7	Həmzəyev Çingiz	8	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
8	Nizamzadə Teymur	8	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
9	Tağıyev Raul	8	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
10	Əzizli Ceyhun	8	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
11	Bədəlov Sərhəddin	4	\N	1	\N	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
12	Nəcəfov Kamran	5	\N	2	\N	\N	\N	\N	\N	99EA650	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
13	Həmzəyev Fazil	7	\N	2	1	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
14	Əfəndiyev Füzuli	7	\N	2	2	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
18	Nəcəfova Nərmin	8	\N	2	1	nnecefova@emlak.gov.az	116	\N	609	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
15	Xəlilov Binnət	7	\N	2	3	\N	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
16	Məmmədova Günel	9	\N	2	3	gmammedova@emlak.gov.az	116	\N	609	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
17	Əlili İnci	9	\N	2	2	ielili@emlak.gov.az	116	\N	609	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
19	Qəribov Mehrac	9	\N	2	3	mqeribov@emlak.gov.az	116	+994 51-633-67-09	609	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
20	Nağıyev Elnur	8	\N	2	3	elnurnagiyev@emlak.gov.az	116	+994 70-891-55-99	609	90NV178	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
21	Musayeva-Miriyeva Sevda	8	\N	2	1	smusayeva@emlak.gov.az	116	\N	609	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
22	Vəliyeva Aysel	9	\N	2	2	ayselvaliyeva@emlak.gov.az	\N	\N	612	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
23	Adıgözəlova Şəbnəm	9	\N	2	2	shadigozelova@emlak.gov.az	\N	\N	612	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
24	Rüstəmova Gülsüm	9	\N	2	2	grustemova@emlak.gov.az	\N	\N	612	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
25	Hüseynov Ceyhun	9	\N	2	3	ceyhunhuseyni47@gamil.com	160	+994 51-705-78-33	533	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
26	Abbasov Tehran	9	\N	2	3	tehran.abbasov.9494@gmail.com	160	+994 70-940-00-47	533	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
27	Gülməmmədov Toğrul	10	\N	2	3	tgulmemmedov8@gmail.com	160	+994 50-876-13-17	533	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
28	Ağazadə Coşqun	11	\N	2	3	Joshgunagazade47@gmail.com	160	+994 51-511-50-60	533	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
29	Eyvazova Arzu	11	\N	2	3	arzue77@gmail.com	160	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
30	Qəribova Arzu	9	\N	2	3	aqeribova@emlak.gov.az	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
31	Həsənova Xavər	9	\N	2	3	xhesenova@emlak.gov.az	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
32	Behbudova Könül	9	\N	2	3	konuulbehbudova@gmail.com	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
33	Tarverdiyeva Şəbnəm	9	\N	2	3	tarverdiyevashabnam@gmail.com	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
34	Xəlilova Banu	9	\N	2	2	bxelilova@emlak.gov.az	144	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
35	Rəhimova Günel	9	\N	2	2	grehimova@emlak.gov.az	144	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
36	Nəsibli Gülcan	9	\N	2	2	gnesibli@emlak.gov.az	144	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
37	Əlizadə Dəniz	8	\N	2	3	denizelizade@emlak.gov.az	144	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
38	Tağıyeva Sevinc	8	\N	2	3	sevinctagiyevaa@gmail.com	\N	\N	\N	\N	2026-08-13 10:38:26.106515+04	2026-08-13 15:09:07.084209+04
\.


--
-- Data for Name: portal_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_users (id, username, email, role, password, is_active, created_at) FROM stdin;
2	Admin	admin@company.com	admin	$2b$10$bfKUDUWsLkf96lrl..Slh.Dby0pFDM4r0ZZDGzyvi4RxE9CK/EruS	t	2026-08-13 10:34:32.34942+04
\.


--
-- Data for Name: positions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.positions (id, name, created_at) FROM stdin;
1	Direktor	2026-08-13 10:34:32.34942+04
2	Direktor müavini	2026-08-13 10:38:26.106515+04
3	Baş mühəndis	2026-08-13 10:38:26.106515+04
4	Əməyin mühafizəsi üzrə mühəndis	2026-08-13 10:38:26.106515+04
5	Şöbə müdiri	2026-08-13 10:38:26.106515+04
6	Şöbə müdirinin müavini	2026-08-13 10:38:26.106515+04
7	Sektor müdiri	2026-08-13 10:38:26.106515+04
8	Aparıcı mühəndis	2026-08-13 10:38:26.106515+04
9	Mühəndis	2026-08-13 10:38:26.106515+04
10	Texnik	2026-08-13 10:38:26.106515+04
11	Operator	2026-08-13 10:38:26.106515+04
12	Kargüzar	2026-08-13 10:38:26.106515+04
13	Laboratoriya müdiri	2026-08-13 10:38:26.106515+04
14	Hüquq məsləhətçisi	2026-08-13 10:38:26.106515+04
15	Sənədlərlə iş üzrə mütəxəssis	2026-08-13 10:38:26.106515+04
16	Baş mühasib	2026-08-13 10:38:26.106515+04
17	Aparıcı iqtisadçı	2026-08-13 10:38:26.106515+04
18	İqtisadçı	2026-08-13 10:38:26.106515+04
19	Mühasib	2026-08-13 10:38:26.106515+04
20	Təsərrüfat işləri üzrə mütəxəssis	2026-08-13 10:38:26.106515+04
21	Anbardar	2026-08-13 10:38:26.106515+04
22	Elektrik avadanlıqlarına xidmət üzrə elektrik	2026-08-13 10:38:26.106515+04
23	Kadrlar üzrə aparıcı mütəxəssis	2026-08-13 10:38:26.106515+04
24	Kadrlar üzrə mütəxəssis	2026-08-13 10:38:26.106515+04
\.


--
-- Data for Name: sectors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sectors (id, name, dept_id, created_at) FROM stdin;
1	Coğrafi informasiya sistemləri sektoru (CİS)	2	2026-08-13 15:07:55.268599+04
2	Kadastr məlumatlarının idarə edilməsi sektoru	2	2026-08-13 15:07:55.268599+04
3	Fotoqrammetriya sektoru	2	2026-08-13 15:07:55.268599+04
\.


--
-- Data for Name: system_positions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.system_positions (id, name, created_at) FROM stdin;
\.


--
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_id_seq', 2, true);


--
-- Name: employee_edit_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_edit_requests_id_seq', 1, true);


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_id_seq', 38, true);


--
-- Name: portal_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_users_id_seq', 2, true);


--
-- Name: positions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.positions_id_seq', 24, true);


--
-- Name: sectors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sectors_id_seq', 3, true);


--
-- Name: system_positions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.system_positions_id_seq', 1, false);


--
-- Name: departments departments_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_name_key UNIQUE (name);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: employee_edit_requests employee_edit_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_edit_requests
    ADD CONSTRAINT employee_edit_requests_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: portal_users portal_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_users
    ADD CONSTRAINT portal_users_pkey PRIMARY KEY (id);


--
-- Name: portal_users portal_users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_users
    ADD CONSTRAINT portal_users_username_key UNIQUE (username);


--
-- Name: positions positions_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_name_key UNIQUE (name);


--
-- Name: positions positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);


--
-- Name: sectors sectors_name_dept_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_name_dept_unique UNIQUE (name, dept_id);


--
-- Name: sectors sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_pkey PRIMARY KEY (id);


--
-- Name: system_positions system_positions_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_positions
    ADD CONSTRAINT system_positions_name_key UNIQUE (name);


--
-- Name: system_positions system_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_positions
    ADD CONSTRAINT system_positions_pkey PRIMARY KEY (id);


--
-- Name: employees employees_dept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_dept_id_fkey FOREIGN KEY (dept_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- Name: employees employees_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id) ON DELETE SET NULL;


--
-- Name: employees employees_sector_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.sectors(id) ON DELETE SET NULL;


--
-- Name: employees employees_system_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_system_position_id_fkey FOREIGN KEY (system_position_id) REFERENCES public.system_positions(id) ON DELETE SET NULL;


--
-- Name: sectors sectors_dept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_dept_id_fkey FOREIGN KEY (dept_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict UcqoKN0jaaiBqakSTbkvDQewS1qBrSuypKpIsJgbFBsL5FXS1PCuyVXLlm0V2So

