-- ==========================================
-- Database Schema for KYLTM Employee Portal
-- PostgreSQL Dialect
-- ==========================================

-- 1. Departments Domain Table
CREATE TABLE IF NOT EXISTS departments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT departments_pkey PRIMARY KEY (id)
);

-- 2. Sectors Domain Table (belongs to a department)
CREATE TABLE IF NOT EXISTS sectors (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    dept_id bigint NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sectors_pkey PRIMARY KEY (id),
    CONSTRAINT sectors_name_dept_unique UNIQUE (name, dept_id)
);

-- 3. Positions Domain Table (global positions list)
CREATE TABLE IF NOT EXISTS positions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT positions_pkey PRIMARY KEY (id)
);

-- 3b. System Positions (Direktor, Şöbə Müdiri, etc.)
CREATE TABLE IF NOT EXISTS system_positions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT system_positions_pkey PRIMARY KEY (id)
);

-- 4. Employees Table (references domain IDs)
CREATE TABLE IF NOT EXISTS employees (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    position_id bigint REFERENCES positions(id) ON DELETE SET NULL,
    system_position_id bigint REFERENCES system_positions(id) ON DELETE SET NULL,
    dept_id bigint REFERENCES departments(id) ON DELETE SET NULL,
    sector_id bigint REFERENCES sectors(id) ON DELETE SET NULL,
    email text,
    intphone text,
    mobile text,
    room text,
    car_plate text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

-- 5. Employee Edit Requests Table
CREATE TABLE IF NOT EXISTS employee_edit_requests (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id integer NOT NULL,
    employee_name text,
    old_data jsonb,
    new_data jsonb,
    status text DEFAULT 'pending'::text,
    requested_by text,
    requested_at timestamp with time zone DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT employee_edit_requests_pkey PRIMARY KEY (id)
);

-- 6. Portal Users Table
CREATE TABLE IF NOT EXISTS portal_users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    email text NOT NULL,
    role text NOT NULL DEFAULT 'user'::text,
    password text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT portal_users_pkey PRIMARY KEY (id),
    CONSTRAINT portal_users_username_key UNIQUE (username)
);
